### ISSUE TITLE
Can't Install in Docker

### ISSUE THREAD

**Issue by ModestTG** [node-red-contrib-themes/dracula#5]
# Problem/Motivation
I am trying to install this theme in docker. When I get into the container and try and install, I get a permission error that I can't fix

> (Why the issue was filed)
I do not know why this permission issue is occurring or how to fix it

- Theme version: latest? I don't see any theme versioning on the project page. Tried to install on 11/13/2021
- Node-RED version: 2.1.3
- Platform/OS: 
  - Platform: Docker version 20.10.10, build b485636
  - Platform: Docker-compose version 1.25.4, build 8d51620a
  -  OS: Linux 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Browser: Firefox 94.0.1 (64-bit)

## Steps to reproduce
Create node-red with the following compose options
```YAML
version: "3.7"
services:
  nodered:
    image: nodered/node-red:latest
    container_name: NodeRed
    restart: unless-stopped
    user: "$PUID:$PGID"
    networks:
      - automon
    ports:
      - "1880:1880"
    volumes:
      - "/home/docker/container_data/nodered/data:/data"
    environment:
      - TZ=$TZ
networks:
  automon:
    driver: bridge
```
$PUID:$PGID equates to 1020:1002.

Login to container to try and install
```Shell
docker exec -it NodeRed bash
```
Run the command to install
```Shell
npm install @node-red-contrib-themes/dracula
```
I get the following error
```Shell
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1020:1002 "/.npm
```
the `/.npm` folder doesn't exist from what I can see. I see that this has to be a permissions issue, but I don't know how to solve this. Any help would be appreciated!

> (How can someone else see it happen. If possible,
Run steps to reproduce
> add one or more screenshots)

![error](https://user-images.githubusercontent.com/12620790/141670109-697e5a35-be65-4472-866f-14a4ad151cf2.png)
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe it here)

Potential documentation updates. Depends on how this is resolved.

**Comment by bonanitech** [comment]
By the error message you're getting, you're probably trying to install the package in the wrong directory.
I think you have to install the package into `/data` inside the container in this case.

**Comment by ModestTG** [comment]
@bonanitech Thanks for the quick reply! I tried this using the following method, but got the same error
```Shell
bash-5.0$ npm install --prefix /data @node-red-contrib-themes/dracula
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1020:1002 "/.npm"
```

Screenshot
![error2](https://user-images.githubusercontent.com/12620790/141699146-7338208d-b971-487e-897d-7c43ac9fff1f.png)

Is there another way to specify this directory?

**Comment by bonanitech** [comment]
```shell
cd /data
npm install @node-red-contrib-themes/dracula
```

**Comment by ModestTG** [comment]
@bonanitech I got the same error when switching into that directory. Do I need to install these packages as root? when I run `whoami` it shows as the 1020, which is the user I have for `user: $PUID` in my compose file

**Comment by ModestTG** [comment]
I was able to get this installed. I had to login to the container as root, and then install the container. Here are the steps I took:

```
docker exec -it -u root NodeRed bash
cd /data
npm install @node-red-contrib-themes/dracula
```

This was most likely required since I chose to run the container as another user so I can access the files with my user and not have them be restricted to root (by setting the `user` attribute in docker-compose). This issue can be closed. Thanks for your help!

**Comment by ksmarty** [comment]
As an addendum to this, here is my docker compose to get the theme to remain installed after reboot/update:

```yaml
---
version: "2.3"
services:
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - 1880:1880
    volumes:
      - ${USERDIR}/node-red:/data:rw
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        cd /usr/src/node-red
        npm i @node-red-contrib-themes/dracula
        npm start --cache /data/.npm -- --userDir /data
```
